### ISSUE TITLE
If there is invalid characters in directory path, package will go into an infinite loop.

### ISSUE THREAD

**Issue by niyarlatotep** [simonlc/async-mkdirp#1]
Example:
Windows path:

```js
async foo(){
  await mkdir(`:::`);
}
```

will not throw an exception, just do infinite loop.

**Comment by simonlc** [comment]
Thank you for reporting this bug. It seems to be related to an issue in libuv here: libuv/libuv#1088. The patch is merged into master, but it isn't in any version of Node.js yet.

I propose using the [solution from make-dir](https://github.com/sindresorhus/make-dir/blob/master/index.js#L13-L23). It doesn't make sense to include it in this project as the goal is to remain lean and work on the latest versions of Node.js.

I suggest include the fix linked above in your projects using Windows, or simply use [sindresorhus/make-dir](https://github.com/sindresorhus/make-dir/) directly .

**Comment by niyarlatotep** [comment]
@simonlc thank you for responce. Think it's not connected with bug in libuv. It's because of 
` case 'ENOENT'` in this package. Symbols like ": / \ *" and so on, is diprecated in Windows OS so fs.mkdir, cannot to create folder, and throw 'ENOENT' exception, but this program do loop on 'ENOENT' exception and try making directory again and again and again. I solved it by not checking on 'ENOENT' but checking on 'EEXIST'

```js
async function myMkdir(directoriesPath) {
    //make directory path, if parent directories exists yet
    const arrayOfDirectories = directoriesPath.split(path.sep);

    for (let i=1; i<=arrayOfDirectories.length; i++){
        let iterationArray = arrayOfDirectories.slice(0, i);
        let newPath = iterationArray.join(path.sep);
        try {
            await mkdir(newPath);
        } catch (error){
            if (error.code === 'EEXIST'){
                const stats = await stat(newPath);
                if (!stats.isDirectory()) {
                    throw new Error(error);
                }
            } else {
                throw new Error(error);
            }
        }
    }
}
```

**Comment by L1lith** [comment]
I ran into issue as well, it doesn't seem like it should have been closed.

**Comment by simonlc** [comment]
> I ran into issue as well, it doesn't seem like it should have been closed.

Please see my comment above. It proposes some solutions that were not the right fit for this project. Also note that this module has been deprecated.

**Comment by niyarlatotep** [comment]
@L1lith  You can just use my function "myMkdir" presented above it should work.
